name: OrangeHRM Selenium E2E
 
on:
  workflow_dispatch:
  push:
    branches:[main]
  pull_request:
 
jobs:
  e2e:
    runs-on: ubuntu-latest
 
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: >-
          --shm-size=2g
          --health-cmd="curl -f http://localhost:4444/status"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20
 
    env:
      APP_URL: https://opensource-demo.orangehrmlive.com/
      BROWSER: chrome
      HEADLESS: true
      REPORT_DIR: ${{ github.workspace }}/TestResults
      SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
 
      - name: Restore
        run: dotnet restore
 
      - name: Build
        run: dotnet build --no-restore
 
      - name: Run E2E tests
        run: dotnet test --no-build --filter "TestCategory=smoke|TestCategory=regression"
 
      - name: Upload Extent report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: orangehrm-extent-report
          path: TestResults